### ISSUE TITLE
Simple API for creating store + set event

### ISSUE THREAD

**Issue by PFight** [effector/effector#429]
## Proposal

I often create stores with single event, that simple set value of the store. Something link this:

```
let $count = createStore(0);
let setCount = createEvent();
$count.on(setCount, (_, count) => count);
```
Writing this again and again is quite verbose. Maybe I doing something wrong, dont know... But it would be nice to have API, that reduces these 3 rows to one.

**Comment by zerobias** [comment]
Most of the methods accept stores as targets, including sample, guard, forward and split, so you doesn’t need additional event to connect dataflows to given stores

Even more, when you *describe what happens* instead of *what need to do*, you doesn’t need to think about store updates at all

Compare:

```js
const fetchFriends = createEffect()
const setFriends = createEvent()
const friends = createStore([])
  .on(setFriends, (_, friends) => friends)

fetchFriends.doneData.watch(friends => {
  setFriends(friends)
})

```

vs

```js
const fetchFriends = createEffect()
const friends = createStore([])
  .on(fetchFriends.doneData, (_, friends) => friends)
```

And as a shorthand, you can create store *from* given event or effect with [restore](https://effector.dev/docs/api/effector/restore)

With restore, previous example will looks like this:
```js
const fetchFriends = createEffect()
const friends = restore(fetchFriends, [])
```

So it’s work a bit in reverse, to avoid setStore antipattern

**Comment by PFight** [comment]
Looks like I should learn more about effector philosophy, but, what I can see - anyway, I often need to create events, attached to store. How about function createEvent in store?

    // Current
    const store = createStore(0);
    const event = createEvent();
    store.on(event, (s, args) => reducer(s, args));

    // Suggested
    const store = createStore(0);
    const event = store.createEvent((s, args) => reducer(s, args));

We already have similar function createApi, but I can't see how to use it in my application.

**Comment by zarabotaet** [comment]
@PFight You can easily create your own fabric around createApi 
`const reevent = (store, reducer = (store, payload) => payload) =>
  createApi(store, {
    event: reducer,
  }).event

const $store = createStore(0)

const change = reevent($store)`
https://share.effector.dev/qEsBAkeY

But in the effector world more conventional way is to create events explicitly by createEvent fabric and use restore for reducing boilerplate.
