### ISSUE TITLE
`clock` in `split`

### ISSUE THREAD

**Issue by igorkamyshev** [effector/effector#537]
## Proposal

Add `clock` to `split`.

## Use case

All use cases from `guard` and `sample` with `clock` 🌚

**Comment by zzzorgo** [comment]
@zerobias Hi, I couldn't find in the docs and by playing around with `split` how to get the payload of the event passed as `clock` to `split`? I am always getting `undefined` when trying to access it the same way as with the `sample`

**Comment by YanLobat** [comment]
Unfortunately only payload from source is available, clock in split for now is just a trigger

**Comment by YanLobat** [comment]
@zzzorgo unfortunately `clock` is available in split as a trigger only, payload passes from `source` field

**Comment by zzzorgo** [comment]
@YanLobat Thank you for you response! Could you please also clarify whether payload of `clock` is omitted by design or it is just  a thing in the backlog? If it is by design what is the motivation?

I will elaborate a bit why I am asking: I have the case where an event (event1) is fired by, lets say, a react component. This event should split into two events (event2 and event3) depending on the store's current state and pass its payload to the target. I have two workaround to achive the same outcome:

1. Using `sample` to generate an event carring both store's state and event1 payload and use it as a `source` inside `split` (without using `clock`) - the downside is that this solution is quite wordy especially considering the fact that `split` has `clock` already but just not passes the paylod of it 
2. Using two independant `sample`s instread of `split` - the downside is that this solution doesn't convey the idea of splitting the event into two events as `split` does

**Comment by YanLobat** [comment]
@zzzorgo `clock` payload is omitted due to the complexity of the implementation atm. but surely it's a future backlog!

yeah if it not possible to have all the necessary payload in source only, remained `clock` field void, then I suppose to use 2nd option.
imo these 2 options are more or less the same.
