### ISSUE TITLE
Add SWC plugin

### ISSUE THREAD

**Issue by domosedov** [effector/effector#546]
Proposal: create an "effector/swc-plugin" that is similar to "effector/babel-plugin".

[https://swc.rs/docs/usage-plugin](https://swc.rs/docs/usage-plugin)

[Next.js 12](https://nextjs.org/blog/next-12#faster-builds-and-fast-refresh-with-rust-compiler) includes a brand new Rust compiler that takes advantage of native compilation. The compiler is built on [SWC](https://swc.rs/), an open platform for the next generation of fast tooling.

**Comment by zerobias** [comment]
> Warning: Plugin apis are going to be deprecated in v2. With v2, swc will provide a rust-based plugin api instead 😒

Otherwise it’ll going to be a huge improvement for effector

**Comment by zerobias** [comment]
so, we need to wait for v2 and write the implementation. plugins written in rust seem to be an interesting experience; the only thing I was wary of was the complete lack of plugins

btw, the last thing i expected from effector development was code written in rust 😅

**Comment by sergeysova** [comment]
I have some experience in Rust and writing plugins.

**Comment by zerobias** [comment]
Looks like swc v2 is a typical overextended, [too-early-announced](https://github.com/swc-project/swc/issues/1321) project and it definitely will not be used in nextjs 12.

And vercel would not be vercel without a mad farce: they implement their own plugins. This is the __worst__-case scenario, since they do not provide any api for creating our own plugins (who the hell would ever need that?).
The only real solution is to politely ask them [here](https://github.com/vercel/next.js/discussions/30174) and hope they will implement that (they will not)
The ecosystem we deserve. Vendor lock we all deserve

**Comment by domosedov** [comment]
Looks like the Hype Driven Development =)
No docs, no examples.
[https://twitter.com/flybayer/status/1454547398521393153](https://twitter.com/flybayer/status/1454547398521393153)

**Comment by zerobias** [comment]
I tell vercel about effector, please [upvote an answer](https://github.com/vercel/next.js/discussions/30174#discussioncomment-1568991)
