### ISSUE TITLE
jest.fn mock looses store's scope if event called from setInterval

### ISSUE THREAD

**Issue by zzzorgo** [effector/effector#558]
Hello!

I have started exploring effector and stack with an issue which I don't understand. My experimental feature is simple: start and stop interval (native setInterval from JS). Every time interval calls callback function some http-request should be send. The whole thing works fine but I am struggling to write tests to it. My test is "if timer has started and 3 seconds have passed then http-requesting function should be called with expected parameters". Expected parameters include value being read from am store. In my test I a forking initial scope and as a result every scope related assertion is fine (using scope.getState), but not for mock calls somehow.

**What is the current behavior:**
jest.fn mock called with NaN

**Please provide the steps to reproduce and if possible a minimal demo of the problem via https://share.effector.dev, https://codesandbox.io or similar**
I have a repository with minimal example https://github.com/zzzorgo/effector-issue/
1. Clone repository
2. Run command `yarn install && yarn jest`

**What is the expected behavior:**
jest.fn mock called with not NaN number

**Which versions of effector packages, and which browser and OS are affected by this issue? Did this work in previous versions of effector?:**
effector@22.1.2
jest@26.6.0
nodejs@14.17.5

**Comment by AlexandrHoroshih** [comment]
Hi!

effector scopes feature is built on stack-based approach (similar to react-hooks for e.g.) and because of that scope should be set explicitly at the launch moment

There is a special api to handle cases, when events are called by external source: [scopeBind](https://effector.dev/docs/api/effector/scopeBind)

You can call it inside your `intervalFx` to bind update event to the scope and then use this binded version of event inside `setInterval`

Also you may want to look at `interval` method from [patronum](https://github.com/effector/patronum) instead

**Comment by zzzorgo** [comment]
Thank you, it worked! I was looking at `scopeBind`, but used it in another way and got an error about calling it from a wrong place (not in forked watch). Also example in the documentation and the documentation itself doesn't tell much about `scopeBind` use cases, may be add this case to it?
