### ISSUE TITLE
`sample` typings error

### ISSUE THREAD

**Issue by meff34** [effector/effector#600]
**What is the current behavior:**
The `sample` operator allows sampling from `unknown` to narrower types.

**Steps to reproduce:**
[www.typescriptlang.org/play](https://www.typescriptlang.org/play?ssl=13&ssc=24&pln=13&pc=73#code/JYWwDg9gTgLgBAbzgYygUwIYzQUQG5oB2MANHAGbQDuGUAJmQM4bgA2acAvhVBCHAHI05cmmQxoAgFBTkEQo3hoQwGAFVCAa0IQqhOAF4U6LLgLEAPAFctOvQD4AFAEpZ8xXHTI0wAgDkrEAAjNChDY0xsfCIYC0JAkKgnVylmNjRHBCk4OAB6XLgAARhGAFo0AA8wMRhyqF4oAC44GytGNDo4OmAvGF8OQBlybLhGCCsob2blVQ1tXUISYZhaAHM0GGavH38E0MXOFMooGnpM4fyikvKqmrqG5pgAT2rBGzm9AThgRjgdeAxGIxgCtCBgguw4BJIc8OAJ4sFQgIAHRwQCg5MNyLwQFMVOpbPMyEsIJsxNs0AEEVB9s4gA)

```typescript
import { createEvent, forward, sample } from 'effector'

const emitUnknown = createEvent<unknown>()
const receiveNumber = createEvent<number>()

sample({
  // @ts-expect-error: unused directive ❌
  source: emitUnknown,
  target: receiveNumber,
})

forward({
  // @ts-expect-error: type 'unknown' is not assignable to type 'number'. ✅
  from: emitUnknown, 
  to: receiveNumber,
})
```

**What is the expected behavior:**
The "sample" is expected to work identically to the "forward" in this case: throw compilation error "type 'unknown' is not assignable to type 'number'"

**Versions:**
Reproduces on effector@22.1.2 and typescript@4.5.4

**Comment by zerobias** [comment]
Already fixed in master, I added a [test](https://github.com/effector/effector/blob/c4c9c53e3120e073e892b9a328eecb4b9a394161/src/types/__tests__/effector/sample/sample.test.ts#L806) for your case and it has pretty clear error message:
![image](https://user-images.githubusercontent.com/15912112/149415322-0967a953-0b2f-45af-9ff6-de2d9ddc31fc.png)

The fix will be published in next minor release
