### ISSUE TITLE
`sample` - incompatible unit in target appears as an error in `source`

### ISSUE THREAD

**Issue by uulaal** [effector/effector#623]
In this [sandbox](https://codesandbox.io/s/pensive-dew-ss21e?file=/src/index.ts) you can see that in v22.1.2 incompatible unit in target is error-highlighted by itself, but in v22.2.0 the `source` becomes highlighted with error text "source should extend target type", which is less infomative than highlighting a specific unit in target

**Comment by zerobias** [comment]
I agree that custom errors should force error on proper field, as there are a lot of obvious cases, in which we could select another field to highlight. This is possible and I suggest to improve that in next minor release


I see a more general complaint here, so briefly on the motivation behind this decision:

## Why this works in that way


There was **no way to further improve the old types**: we would get a good old-fashioned error message in one case, get an error in the right case the next time, and finally miss the error in the wrong case. Many popular and important cases were broken in very different ways without a chance to improve, resulting in a half-hearted solution

This is a **design limitation in TS**, thus we've made a custom errors.

Custom errors are actually custom type comparators to _find_ errors, they just have to print out what they've found in unusual way. Without them typescript merge `target` types from arrays before comparison, so this case becomes valid:

```ts
sample({
  clock: Store<{name: string; age?: number}>,
  target: [Event<{name: string}>, Event<{name: string; age: number}>]
})
```

Because of that behavior:

```ts
[{name: string}, {name: string; age: number}]
// →
{name: string} | {name: string; age: number}
// →
{name: string; age?: number}
```

Even more, if some of targets has any type, whole expression would **lost ability to find errors**:

```ts
[{name: string}, {name: string; age: number}, any]
// →
{name: string} | {name: string; age: number} | any
// →
any
```

We fought against this behavior for a long time, but the possibilities to resist it in the old paradigm were exhausted

And this is just single example from vast ocean of edge cases which could be leveraged by precise comparison of `source/clock` and `target` arrays one-by-one: if we found some mismatch, we return a special object fields of which talk with users as typescript unable to properly do so.

## How to read custom error messages

All the information is placed next to error text

```ts

sample({
  source: $number, /* Src */
  target: [
    numberEvent, /* Trg1 */
    stringEvent, /* Trg2 */
    anyEvent, /* Trg3 */
  ]
})

{
  error: "source should extend target type",
  targets: [
    Event<number>, /* Trg1 */
    { sourceType: number /* Src */, targetType: string /* Trg2 */},
    Event<any>, /* Trg3 */
  ]
}
```

"targets" is array from your `target` field, in which each incorrect type replaced by object {sourceType: _type of source unit_; targetType: _type of that target unit_}

![image](https://user-images.githubusercontent.com/15912112/152257297-48bec210-4485-4b27-9380-61e7856bcd46.png)


I hope this brings you some clarity

**Comment by sergeysova** [comment]
@uulaal Can you check this issue on the latest effector version?

**Comment by sergeysova** [comment]
Effector is going to release the new major version.
This case cannot be reproduced, because of much minor versions with the typings fixes.
