### ISSUE TITLE
TypeScript errors using sample with effector@22.2.0

### ISSUE THREAD

**Issue by Rastraponovich** [effector/effector#631]
**What is the current behavior:**
TypeScript errors using sample with effector@22.2.0

A minimal [demo](https://tsplay.dev/mL4OAm) of the problem.

**What is the expected behavior:**
No TypeScript errors
**Which versions of effector packages, and which browser and OS are affected by this issue? Did this work in previous versions of effector?:**
typescript: 4.5.4 (playground). I have the same problem in my project under TypeScript 4.5.2\4.5.4

**Comment by zerobias** [comment]
Expected behavior is a __single error__, your example must perform null check before use `currentTrackId`.

[Correct example](https://www.typescriptlang.org/play?ts=4.4.4#code/LAKAlgtgDg9gTgFwAQG8DGcCmBDBmCiAbpgHYIA0GOeAygvJuQM7bQA2mAvkgGZwwQkAckw8emNPThDQCAJ5RMSAHIBXNm2wAjDgB4AKgD4kAXiT6kAHyQl1bUGhgkmyNAAsJAawAKWQvrhsNE8AYTYwYMwAE1MkKlwCYjJdWwgtTDhDAAoASgcnFyQAEihNOQAZMEKzeNopTF1sEjkAbQBdbPa8kEdnZCK0VTgsMm8y6ICgzwBJEijMAA8x7Dlw6risBLoGXTUNbT1U9Mzs2w1u3sKmTA5JSeDZ5Yqq5BrNvCJSBBTVNIzs7qgFjsTBZFCgJCQuJsGDBABccQ8wV8mH8gWCYQinmi5AhUKYMCGaEwCJaJTKlRc5GKg2GXyeE3RMzmiyeawQbVxIChvBICKyLVKK0pFDiQxGCHuMyinKQAH0cqZjODuTyoWAeEgsrSJVLpjETIabHYrNYdV89QajQAGRUqtUOpBYBBDEhIIXPFwAOg4JAA5gg3EgALRIACMeIdnEjaudrrFdLIlpD4ZjnC5PIQ2DgfswCAR11ukqZjwpLy5nByQA) has no errors in both 4.4.4 and 4.5.2, fail only in 4.5.4 which has a bug that will be fixed in 4.6.0
