### ISSUE TITLE
How to get previous state on store update?

### ISSUE THREAD

**Issue by PFight** [effector/effector#990]
I need to raise effect on store value change with two arguments: new value and old value. Something like this:

myStore.updtaes.watch((newValue, oldValue) => myEffect(newValue, oldValue));

How to make this? Watch provides access only to newValue.

**Comment by yumauri** [comment]
First of all, I want you to know, that during team's internal discussion about adding operator for that into [`patronum`](https://patronum.effector.dev/) library, we came to conclusion, that usually, if you think you need a previous value of a store — there is _something wrong in your application's logic_, and it could be done without it.

But I personally have this operator in my current application source code, so I can share it with you. Or at least an idea of it.

This is a bit tricky, but main idea — you need another store, which will contain both values — current and previous — and shift it as soon as new value arrives.

This could look like this:
```js
function previous($store) {
  const $stack = createStore([$store.defaultState])

  sample({
    clock: $store,
    source: $stack,
    fn: ([current, previous], value) => [value, current],
    target: $stack,
  })

  return $stack.map(values => values[1])
}
```

It could be used like this:
```js
const inc = createEvent()
const $store = createStore(1).on(inc, x => ++x)
const $previous = previous($store)

const fx = createEffect(console.log)

sample({
  clock: $store,
  source: $previous,
  fn: (previous, current) => ({ current, previous }),
  target: fx
})

inc() // {current: 2, previous: 1}
inc() // {current: 3, previous: 2}
inc() // {current: 4, previous: 3}
```

This will not work in scope for the first change, if store has different initial value in scope, because `fork` doesn't trigger an update, though...
```js
const scope = fork({ values: [[$store, 42]] })
await allSettled(inc, { scope }) // {current: 43, previous: 1} // <- note this
await allSettled(inc, { scope }) // {current: 44, previous: 43}
await allSettled(inc, { scope }) // {current: 45, previous: 44}
```

I'm not sure how to fix this, maybe someone will answer better than me.

**Comment by zerobias** [comment]
We added [previous](https://patronum.effector.dev/methods/previous/) method to patronum, feel free to use it 👍 
This implementation avoids caveats like in a post above, so we suggest using it instead of any home-made solutions
