### ISSUE TITLE
Question about updates to store with same value

### ISSUE THREAD

**Issue by mkhoussid** [effector/effector#998]
Suppose the following:

```
const data = createStore(null);

const setData = createEvent();

data.on(setData, (_, payload) => payload);
```
If I keep calling data `setData` like so:

```
setData(null);
setData(null);
setData(null);
```
Does `data` get updated, or is there a built in check for whether or not the payload value is different from the current value? Or do I have to specify [`updateFilter`](https://effector.dev/docs/api/effector/createstore/#example-with-updatefilter) explicitly?

**Comment by yumauri** [comment]
You could simply check it yourself in our playground:
https://share.effector.dev/yoWQ1ahE
(currently there is an issue with playground with double execution after you folow the link, but if you edit the code in any way, even by simply typing space, it will recalculate correctly)

By default, values are compared using strict equality. `null === null` is true, and because of that store will not be extra updated.
